apiVersion: v1
kind: Secret
metadata:
  name: kafdrop-secret
  namespace: demo
stringData:
  kafka.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="a8YzuSYRnD~(AwMb";