apiVersion: v1
kind: Service
metadata:
  name: redpanda-ui
  namespace: demo
  labels:
    app: redpanda-ui
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: redpanda-ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda-ui
  namespace: demo
spec:
  selector:
    matchLabels:
      app: redpanda-ui # has to match .spec.template.metadata.labels
  serviceName: "redpanda-ui"
  template:
    metadata:
      labels:
        app: redpanda-ui # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redpanda-ui
        image: docker.redpanda.com/redpandadata/console:latest
        ports:
        - containerPort: 8080
          name: web
        env:
        - name:  KAFKA_BROKERS
          value: "kafka-prod-broker-0.kafka-prod-pods.demo.svc.cluster.local:9092,kafka-prod-broker-1.kafka-prod-pods.demo.svc.cluster.local:9092"
        - name: KAFKA_SASL_ENABLED
          value: "true"
        - name: KAFKA_SASL_USERNAME
          value: admin
        - name: KAFKA_SASL_PASSWORD
          value: a8YzuSYRnD~(AwMb
        - name: CONFIG_FILEPATH
          value: /etc/redpanda/console/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/redpanda/console
      volumes:
      - name: config
        configMap:
          name: redpanda-ui-config
          items:
          - key: config.yaml
            path: config.yaml
        


