apiVersion: v1
kind: Service
metadata:
  name: provectus-ui
  namespace: demo
  labels:
    app: provectus-ui
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: provectus-ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provectus-ui
  namespace: demo
spec:
  selector:
    matchLabels:
      app: provectus-ui # has to match .spec.template.metadata.labels
  serviceName: "provectus-ui"
  template:
    metadata:
      labels:
        app: provectus-ui # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: provectus-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
          name: web
        # volumeMounts:
        # - name: tls
        #   mountPath: /opt/kafka/ssl
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "local"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka-prod-broker-0.kafka-prod-pods.demo.svc.cluster.local:9092,kafka-prod-broker-1.kafka-prod-pods.demo.svc.cluster.local:9092"
        - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
          value: PLAIN
        - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"a8YzuSYRnD~(AwMb\";"
        - name: DYNAMIC_CONFIG_ENABLED
          value: "true"
      # volumes:
      # - name: tls
      #   secret:
      #     defaultMode: 420
      #     items:
      #     - key: truststore.jks
      #       path: client.truststore.jks
      #     - key: keystore.jks
      #       path: client.keystore.jks
      #     secretName: kf-tls-client-cert

